controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotiq85_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

robotiq85_forward_position_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
    interface_name: position
